site_name: PythonTutorial
pages:
- "Home": 'index.md'
- "101": '101.md'
- "201": '201.md'
- "Data Structure":
    - "Object": 'data_object.md'
    - "String": 'data_string.md'
    - "Collection": 'data_collection.md'
    - "Time": 'data_time.md'
